spring:
  datasource:
    url: ${RDS_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 200
    hibernate:
      ddl-auto: update

  mail:
    properties:
      debug: 'true'
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    port: 587

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: local

spring.data.redis:
  port: 6379
  host: 127.0.0.1

---
spring:
  config:
    activate:
      on-profile: prod

spring.data.redis:
  port: 6379
  host: redis