spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smu_poodle?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate: # hibernate ?? ??
      # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
      # if exists drop table ??? ?? ?????? ?? ??.
      ddl-auto: update
    properties: # property ?? ??
      hibernate: # hibernate property ??
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

  config:
    import: application-API-KEY.yml

logging:
  level:
    org.hibernate.type: trace # ?? ???? ????? ???? ??