spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smu_poodle?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate: # hibernate ?? ??
      # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
      # if exists drop table ??? ?? ?????? ?? ??.
      ddl-auto: none
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true

# ?? ?? ??
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # ?? ???? ????? ???? ??